INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Jak rozpętałem II wojnę światową', 72, '1970', 'Franek Dolas trafia jako przymusowy ochotnik do Legii Cudzoziemskiej. Przez pomyłkę dostaje funkcję kucharza. Ogrywa Arabów w grę w trzy karty i zdobywa w ten sposób świeżą żywność.', 'Marian Kociniak, Wacław Kowalski, Jan Świderski', 'PL', '4K', 'KOMEDIA', '7+', '30000', '2021-06-01', '2022-06-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Infiltracja', 151, '2006', 'Agent Costigan musi wejść w mafijne struktury, którymi dowodzi Frank Costello. W czasie gdy stara się on pozyskać zaufanie bossa, do policji podstępem dostaje się przestępca, Sullivan.', 'Leonardo DiCaprio, Matt Damon, Jack Nicholson', 'EN', '8K', 'THRILLER', '12+', '50000', '2021-04-01', '2021-10-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Gladiator', 148, '2000', 'Cesarz Marek Aureliusz chce uczynić generała Maksimusa swoim następcą. Nie podoba się to prawowitemu dziedzicowi Kommodusowi, który postanawia pozbyć się rywala. Maksimus trafia do niewoli.', 'Russell Crowe, Joaquin Phoenix, Connie Nielsen', 'EN', '8K', 'DRAMAT', '16+', '50000', '2021-03-10', '2022-02-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Podziemny krąg', 133, '1999', 'Jack jest młodym biznesmenem. Praca i samotnie spędzane wieczory wypełniają jego życie. Pewnego dnia podczas podróży samolotem poznaje tajemniczego Tylera i postanawia założyć wraz z nim tajny klub.', 'Edward Norton, Brad Pitt', 'EN', '4K', 'DRAMAT', '12+', '30000', '2021-06-01', '2023-01-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Zielona mila', 200, '1999', 'Paul Edgecomb ogląda w telewizji przedwojenny film. Obraz przywołuje odległe wspomnienia, z których Paul zwierza się przyjaciółce. W 1935 r. mężczyzna pracował w jednym z więzień na południu USA.', 'Tom Hanks, David Morse, James Cromwell', 'EN', '8K', 'DRAMAT', '12+', '25000', '2021-03-01', '2023-03-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Wielki Szu', 96, '1983', 'Wielki Szu to pojedynek między mistrzem i uczniem, wielkim karciarzem zmęczonym życiem a młodzikiem nim zafascynowanym, głodnym sukcesu i pieniędzy, trawionym gorączką rodzącego się nałogu.', 'Jan Nowicki, Andrzej Pieczyński, Leon Niemczyk', 'PL', '4K', 'SENSACYJNY', '12+', '10000', '2021-02-01', '2021-11-30');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Szeregowiec Ryan', 169, '1998', '6 czerwca 1944 r., alianci lądują w Normandii. Kapitan John Miller ma stworzyć specjalny oddział, którego zadaniem jest odnaleźć i sprowadzić ostatniego z czwórki braci Ryanów, który przeżył desant.', 'Tom Hanks, Tom Sizemore, Ed Burns', 'EN', '8K', 'WOJENNY', '12+', '14500', '2021-03-01', '2022-01-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Przełęcz ocalonych', 139, '2016', 'Schyłek II wojny światowej. Armia amerykańska toczy walki z Japończykami. Strategicznym celem jest wyspa Okinawa, gdzie trafia oskarżany o tchórzostwo sanitariusz.', 'Andrew Garfield, Sam Worthington', 'EN', '8K', 'WOJENNY', '16+', '12083', '2021-01-01', '2023-12-31');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Szklana pułapka', 132, '1988', 'Grupa terrorystów, która opanowała wieżowiec w Los Angeles, nie przewidziała, że w labiryncie pięter i korytarzy ukrył się policjant John McClane. Rozpoczyna się bezwzględny pojedynek.', 'Bruce Willis, Bonnie Bedelia, Alan Rickman', 'EN', '8K', 'AKCJI', '12+', '10353', '2021-03-10', '2022-02-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Forrest Gump', 142, '1994', 'Na tle powojennych losów Stanów Zjednoczonych ukazana jest historia życiowego nieudacznika, Forresta Gumpa, który mimo to, albo właśnie dlatego, staje się bohaterem narodowym.', 'Tom Hanks, Sally Field, Robin Wright', 'EN', '4K', 'KOMEDIA', '16+', '9068', '2021-06-01', '2023-01-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Powrót do przyszłości', 106, '1985', 'Marty McFly przypadkowo przenosi się w lata 50. XX wieku, gdzie próbuje pogodzić swoich przyszłych rodziców. W przeciwnym razie nigdy się nie narodzi.', 'Michael J. Fox, Christopher Lloyd', 'EN', '3D', 'SCIENCE-FICTION', '7+', '11060', '2021-03-01', '2023-03-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Chłopcy z ferajny', 146, '1990', 'Opowieść o losach Henryego Hilla, który rozpoczął gangsterską karierę jako nastolatek i osiągnął szczyt w hierarchii mafijnej, a zakończył ją jako świadek oskarżenia w procesie bossów.', 'Robert De Niro, Ray Liotta, Joe Pesci', 'EN', '4K', 'SENSACYJNY', '12+', '9861', '2021-02-01', '2021-11-30');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Sami swoi', 80, '1967', 'Opowieść o perypetiach dwóch zwaśnionych rodzin, przesiedleńców zza Buga. Jak niegdyś, mieszkają obok siebie, bo jak sami twierdzą - po co szukać obcego wroga, kiedy swój jest pod ręką.', 'Wacław Kowalski, Władysław Hańcza', 'PL', '4K', 'KOMEDIA', '7+', '21480', '2021-03-01', '2022-01-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Déjà vu', 126, '2006', 'Agent federalny Doug Carlin, obdarzony ponadprzeciętną intuicją, cofa się w czasie, aby pokrzyżować szyki terroryście i zapobiec tragedii.', 'Denzel Washington, Paula Patton, Val Kilmer', 'EN', '8K', 'THRILLER', '12+', '8534', '2021-03-01', '2023-03-01');
INSERT INTO filmy(tytul_filmu, czas_trwania, rok_produkcji, opis_filmu, obsada, wersja_jezykowa, jakosc_filmu, gatunek, ograniczenia_wiekowe, koszt_licencji, dostepny_od, dostepny_do)
 VALUES ('Dawno temu w Ameryce', 116, '1984', 'David i Max kierują grupą przestępczą, robią wielkie pieniądze na nielegalnym handlu alkoholem. Wraz z końcem prohibicji w 1933 r. gang przeżywa kryzys finansowy. Zgrana grupa powoli się rozpada.', 'Robert De Niro, James Woods, Larry Rapp', 'EN', '4K', 'DRAMAT', '16+', '14315', '2021-02-01', '2021-11-30');
